export const states = [
  // States
  { value: 'Gujarat', label: 'ગુજરાત/गुजरात' },
  { value: 'Maharashtra', label: 'મહારાષ્ટ્ર/महाराष्ट्र' },
  { value: 'Rajasthan', label: 'રાજસ્થાન/राजस्थान' },
  { value: 'UttarPradesh', label: 'ઉત્તર પ્રદેશ/उत्तर प्रदेश' },
  { value: 'Bihar', label: 'બિહાર/बिहार' },
  { value: 'WestBengal', label: 'પશ્ચિમ બંગાળ/पश्चिम बंगाल' },
  { value: 'MadhyaPradesh', label: 'મધ્ય પ્રદેશ/मध्य प्रदेश' },
  { value: 'TamilNadu', label: 'તમિલનાડુ/तमिलनाडु' },
  { value: 'AndhraPradesh', label: 'આંધ્ર પ્રદેશ/आंध्र प्रदेश' },
  { value: 'Karnataka', label: 'કર્ણાટક/कर्नाटक' },
  { value: 'Odisha', label: 'ઓડિશા/ओडिशा' },
  { value: 'Telangana', label: 'તેલંગાણા/तेलंगाना' },
  { value: 'Kerala', label: 'કેરળ/केरल' },
  { value: 'Jharkhand', label: 'ઝારખંડ/झारखंड' },
  { value: 'Assam', label: 'અસમ/असम' },
  { value: 'Punjab', label: 'પંજાબ/पंजाब' },
  { value: 'Chhattisgarh', label: 'છત્તીસગઢ/छत्तीसगढ़' },
  { value: 'Haryana', label: 'હરિયાણા/हरियाणा' },
  { value: 'Uttarakhand', label: 'ઉત્તરાખંડ/उत्तराखंड' },
  { value: 'HimachalPradesh', label: 'હિમાચલ પ્રદેશ/हिमाचल प्रदेश' },
  { value: 'Tripura', label: 'ત્રિપુરા/त्रिपुरा' },
  { value: 'Meghalaya', label: 'મેઘાલય/मेघालय' },
  { value: 'Manipur', label: 'મણિપુર/मणिपुर' },
  { value: 'Nagaland', label: 'નાગાલેન્ડ/नगालैंड' },
  { value: 'Goa', label: 'ગોવા/गोवा' },
  { value: 'ArunachalPradesh', label: 'અરુણાચલ પ્રદેશ/अरुणाचल प्रदेश' },
  { value: 'Mizoram', label: 'મિઝોરમ/मिजोरम' },
  { value: 'Sikkim', label: 'સિક્કિમ/सिक्किम' },

  // Union Territories
  { value: 'Delhi', label: 'દિલ્લી/दिल्ली' },
  { value: 'JammuAndKashmir', label: 'જમ્મુ અને કાશ્મીર/जम्मू और कश्मीर' },
  { value: 'Ladakh', label: 'લદ્દાખ/लद्दाख' },
  { value: 'AndamanAndNicobarIslands', label: 'અંડમાન અને નિકોબાર ટાપુઓ/अंडमान और निकोबार द्वीप समूह' },
  { value: 'Chandigarh', label: 'ચંડીગઢ/चंडीगढ़' },
  { value: 'DadraAndNagarHaveliAndDamanAndDiu', label: 'દાદરા અને નગર હવેલી અને દમણ અને દિવ/दादरा और नगर हवेली और दमन और दीव' },
  { value: 'Lakshadweep', label: 'લક્ષદ્વીપ/लक्षद्वीप' },
  { value: 'Puducherry', label: 'પુડુચેરી/पुदुचेरी' },
];
